name: Build and Push RNN to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # Using your provided username
          username: mohitkhairwal2005
          # Referencing the secret name you created (with the typo 'passwors')
          password: ${{ secrets.passwors}}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Tagging the image for your Docker Hub repository
          tags: mohitkhairwal2005/simple-rnn-imdb-review:latest